---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lushihao.
--- DateTime: 2025/10/10 11:01
---
-- 1 参数列表
-- 1.1 商品 id
local productId = ARGV[1]
-- 1.2 用户 id
local userId = ARGV[2]
-- 1.3 订单 id
local orderId = ARGV[3]

-- 2 数据key
-- 2.1 库存key seckill:stock:productId
local stockKey = 'seckill:stock:' .. productId
-- 2.2 订单key seckill:order:productId
local orderKey = 'seckill:order:' .. productId

-- 3 业务逻辑
-- 3.1 判断库存是否充足
if(tonumber(redis.call('get',stockKey)) <= 0) then
    -- 库存不足返回1
    return 1
end
-- 3.2 判断用户是否下过单 SISMEMBER orderKey userId set集合中有没有这个用户
if(redis.call('sismember',orderKey,userId)==1) then
    -- 用户已经下过单了 返回2
    return 2
end
-- 3.3 扣减库存 INCRBY stockKey -1
redis.call('incrby',stockKey,-1)
-- 3.4 用户下单后 需要将用户id 保存到set集合中
redis.call('sadd',orderKey,userId)
-- 3.5 发送消息到队列中 XADD stream.orders * k1 v1 k2 v2 ...  stream.orders是流的名称
redis.call('xadd','stream.orders','*','userId',userId,'productId',productId,'id',orderId)
return 0
